version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: merchant-exchange-backend-db
    restart: always
    environment:
      POSTGRES_DB: stockbar
      POSTGRES_USER: stockbar
      POSTGRES_PASSWORD: stockbar
    ports:
      - "5432:5432"
    volumes:
      - merchant-exchange-backend-pgdata:/var/lib/postgresql/data

volumes:
  merchant-exchange-backend-pgdata:
